import type { Board, User, Project, Meeting, KnowledgeArticle } from "./types"

export const users: User[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@octavertexmedia.demo",
    role: "manager",
    status: "active",
    lastActive: "Just now",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane.smith@octavertexmedia.demo",
    role: "engineer",
    status: "active",
    lastActive: "5 minutes ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-3",
    name: "Alex Johnson",
    email: "alex.johnson@octavertexmedia.demo",
    role: "designer",
    status: "active",
    lastActive: "1 hour ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-4",
    name: "Sarah Williams",
    email: "sarah.williams@octavertexmedia.demo",
    role: "researcher",
    status: "inactive",
    lastActive: "2 days ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "user-5",
    name: "Michael Brown",
    email: "michael.brown@octavertexmedia.demo",
    role: "engineer",
    status: "active",
    lastActive: "3 hours ago",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const initialBoardData: Board = {
  id: "board-1",
  title: "Main Board",
  columns: [
    {
      id: "column-1",
      title: "To Do",
      tickets: [
        {
          id: "ticket-1",
          title: "Implement user authentication",
          description: "Set up user authentication using NextAuth.js with email/password and Google OAuth options.",
          type: "feature",
          priority: "high",
          dueDate: "2023-12-15",
          assignee: users[1],
          comments: [],
          attachments: [],
          createdAt: "2023-12-01T10:00:00Z",
          updatedAt: "2023-12-01T10:00:00Z",
        },
        {
          id: "ticket-2",
          title: "Design landing page mockups",
          description: "Create mockups for the new landing page focusing on conversion and user engagement.",
          type: "task",
          priority: "medium",
          dueDate: "2023-12-10",
          assignee: users[2],
          comments: [],
          attachments: [],
          createdAt: "2023-12-02T09:30:00Z",
          updatedAt: "2023-12-02T09:30:00Z",
        },
        {
          id: "ticket-3",
          title: "Research AI integration options",
          description:
            "Conduct research on available AI APIs and libraries that could be integrated for the assignee suggestion feature.",
          type: "research",
          priority: "low",
          dueDate: "2023-12-20",
          assignee: users[3],
          comments: [],
          attachments: [],
          createdAt: "2023-12-03T14:15:00Z",
          updatedAt: "2023-12-03T14:15:00Z",
        },
      ],
    },
    {
      id: "column-2",
      title: "In Progress",
      tickets: [
        {
          id: "ticket-4",
          title: "Fix responsive layout issues",
          description:
            "Address the layout issues on mobile devices, particularly on the dashboard and user profile pages.",
          type: "bug",
          priority: "high",
          dueDate: "2023-12-08",
          assignee: users[2],
          comments: [
            {
              user: users[0],
              text: "This is becoming a critical issue as more users access from mobile.",
              createdAt: "2023-12-04T11:30:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-04T10:00:00Z",
          updatedAt: "2023-12-04T11:30:00Z",
        },
        {
          id: "ticket-5",
          title: "Implement drag-and-drop functionality",
          description: "Add drag-and-drop functionality to the Kanban board using React DnD or a similar library.",
          type: "feature",
          priority: "medium",
          dueDate: "2023-12-12",
          assignee: users[1],
          comments: [],
          attachments: [],
          createdAt: "2023-12-05T09:00:00Z",
          updatedAt: "2023-12-05T09:00:00Z",
        },
      ],
    },
    {
      id: "column-3",
      title: "Review",
      tickets: [
        {
          id: "ticket-6",
          title: "Optimize database queries",
          description:
            "Review and optimize the current database queries to improve performance, especially for the dashboard.",
          type: "task",
          priority: "medium",
          dueDate: "2023-12-09",
          assignee: users[4],
          comments: [
            {
              user: users[1],
              text: "I've implemented the changes. Please review when you have time.",
              createdAt: "2023-12-06T15:45:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-06T13:00:00Z",
          updatedAt: "2023-12-06T15:45:00Z",
        },
      ],
    },
    {
      id: "column-4",
      title: "Done",
      tickets: [
        {
          id: "ticket-7",
          title: "Set up CI/CD pipeline",
          description: "Configure GitHub Actions for continuous integration and deployment to Vercel.",
          type: "task",
          priority: "high",
          dueDate: "2023-12-05",
          assignee: users[4],
          comments: [
            {
              user: users[0],
              text: "Great work! This will streamline our deployment process.",
              createdAt: "2023-12-05T16:30:00Z",
            },
          ],
          attachments: [],
          createdAt: "2023-12-04T11:00:00Z",
          updatedAt: "2023-12-05T16:30:00Z",
        },
        {
          id: "ticket-8",
          title: "Create user onboarding flow",
          description: "Design and implement the user onboarding flow to improve new user experience.",
          type: "feature",
          priority: "medium",
          dueDate: "2023-12-03",
          assignee: users[2],
          comments: [],
          attachments: [],
          createdAt: "2023-12-01T13:00:00Z",
          updatedAt: "2023-12-03T17:00:00Z",
        },
      ],
    },
  ],
}

export const initialProjects: Project[] = [
  {
    id: "project-1",
    name: "Website Redesign",
    description: "Redesign the company website with improved UI/UX and mobile responsiveness",
    status: "active",
    teamMembers: [users[0], users[1], users[2]],
    createdAt: "2023-11-15T08:00:00Z",
    updatedAt: "2023-12-01T14:30:00Z",
    boardId: "board-1",
  },
  {
    id: "project-2",
    name: "Client Portal Development",
    description: "Build a secure client portal for document sharing and case updates",
    status: "active",
    teamMembers: [users[1], users[3], users[4]],
    createdAt: "2023-11-20T09:15:00Z",
    updatedAt: "2023-12-05T11:45:00Z",
  },
  {
    id: "project-3",
    name: "Mobile App Launch",
    description: "Finalize and launch the mobile application for iOS and Android platforms",
    status: "active",
    teamMembers: [users[0], users[2], users[4]],
    createdAt: "2023-11-25T10:30:00Z",
    updatedAt: "2023-12-07T16:20:00Z",
  }
]

export const initialMeetings: Meeting[] = [
  {
    id: "meeting-1",
    title: "Weekly Team Standup",
    description: "Review progress on active projects and discuss blockers",
    startTime: "2023-12-18T09:00:00Z",
    endTime: "2023-12-18T09:30:00Z",
    organizer: users[0],
    attendees: [users[0], users[1], users[2], users[3], users[4]],
    meetLink: "https://meet.google.com/abc-defg-hij",
    createdAt: "2023-12-10T14:30:00Z",
    updatedAt: "2023-12-10T14:30:00Z",
  },
  {
    id: "meeting-2",
    title: "Website Redesign Planning",
    description: "Discuss next steps for the website redesign project",
    startTime: "2023-12-19T13:00:00Z",
    endTime: "2023-12-19T14:00:00Z",
    organizer: users[1],
    attendees: [users[0], users[1], users[2]],
    meetLink: "https://meet.google.com/jkl-mnop-qrs",
    createdAt: "2023-12-12T10:15:00Z",
    updatedAt: "2023-12-12T10:15:00Z",
  },
  {
    id: "meeting-3",
    title: "Client Portal Review",
    description: "Review the client portal with stakeholders",
    startTime: "2023-12-20T15:00:00Z",
    endTime: "2023-12-20T16:00:00Z",
    organizer: users[3],
    attendees: [users[1], users[3], users[4]],
    meetLink: "https://meet.google.com/tuv-wxyz-123",
    createdAt: "2023-12-13T09:45:00Z",
    updatedAt: "2023-12-13T09:45:00Z",
  }
]

export const initialKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: "article-1",
    title: "Getting Started with Kanban Methodology",
    content: "## Introduction to Kanban\n\nKanban is a visual system for managing work as it moves through a process...",
    category: "Methodology",
    tags: ["kanban", "agile", "productivity"],
    author: users[0],
    createdAt: "2023-11-10T10:00:00Z",
    updatedAt: "2023-12-01T14:20:00Z",
    views: 156,
  },
  {
    id: "article-2",
    title: "Technical documentation standards",
    content: "## Technical documentation standards\n\nClear specs, ADRs, and runbooks help OctaVertex Media ship reliably and onboard engineers faster...",
    category: "Documentation",
    tags: ["engineering", "documentation", "best-practices"],
    author: users[3],
    createdAt: "2023-11-15T08:30:00Z",
    updatedAt: "2023-12-05T09:15:00Z",
    views: 98,
  },
  {
    id: "article-3",
    title: "Using AI in engineering workflows",
    content: "## AI-assisted development\n\nPractical ways to use AI for code review prep, test ideas, and research — with human ownership of outcomes...",
    category: "Technology",
    tags: ["ai", "engineering", "productivity"],
    author: users[4],
    createdAt: "2023-11-20T11:45:00Z",
    updatedAt: "2023-12-07T16:10:00Z",
    views: 214,
  }
]

export const knowledgeCategories = [
  "Methodology",
  "Documentation",
  "Technology",
  "Case Studies",
  "Engineering playbooks",
  "Tutorials",
  "Best Practices",
]
